Iter13
smartfor/metrics pull request #13
Opened 2024-05-04 08:31 UTC by smartfor

2024-05-05 15:47 UTC, edylcrm requested changes

2024-05-05 15:47 UTC, edylcrm commented on cmd/server/main.go
> +				time.Sleep(interval)
А зачем здесь sleep и ticker? Может оставим что-то одно?

2024-05-05 15:47 UTC, edylcrm commented on internal/server/storage/postgres.go
> +		context.TODO(),
Вот сюда было бы правильней передавать контекст из request. Если по какой-то причине клиент отменил запрос, то делать запрос в БД уже не нужно. Это как раз и произойдет если передать контекст из request. 
Так же в контексте может содержаться дополнительная служебная информация для логирования запроса. 
В общем, хорошей практикой считается передавать context из request

2024-05-05 15:47 UTC, edylcrm commented on internal/server/storage/postgres.go
> +		context.TODO(),
Тоже самое про context

2024-05-05 15:47 UTC, edylcrm commented on internal/server/storage/postgres.go
> +		context.TODO(),
И здесь

2024-05-05 15:47 UTC, edylcrm commented on internal/server/storage/postgres.go
> +	query, err := s.pool.Query(context.TODO(), `SELECT FROM gauges`)
И здесь

2024-05-05 15:47 UTC, edylcrm commented on internal/server/storage/postgres.go
> +	query, err := s.pool.Query(context.TODO(), `SELECT (key, value) FROM counters`)
И здесь

2024-05-05 15:47 UTC, edylcrm commented on internal/server/storage/postgres.go
> +	ctx := context.TODO()
И здесь

2024-05-05 15:47 UTC, edylcrm commented on internal/server/storage/postgres.go
> +	pool, err := utils2.Retry(func() (*pgxpool.Pool, error) {
Вообще я не видел, чтобы такая механика ретраев использовалась при работу с БД. 
Как по мне это лишнее, но если нравится как реализовано - можно оставить.

2024-05-06 09:40 UTC, smartfor commented on cmd/server/main.go
> +				time.Sleep(interval)
первый тик вызывается сразу после создания тикера а я хочу чтобы он вызвался через первый интервал и не сразу

2024-05-06 09:43 UTC, smartfor commented on internal/server/storage/postgres.go
> +	pool, err := utils2.Retry(func() (*pgxpool.Pool, error) {
а как было бы правильно? в задании явно было описано что надо с ретраями сделать запросы по сети бд и запись в файлы

2024-05-06 15:09 UTC, edylcrm commented on internal/server/storage/postgres.go
> +	pool, err := utils2.Retry(func() (*pgxpool.Pool, error) {
Вообще на реальных проектах при деградации какой-то части системы ретраи только усугубляют проблему. По этому решение об их использовании нужно очень тщательно прорабатывать и мониторить. 
В целом для ознакомления в пет проекте можно попробовать использовать.

2024-05-06 15:09 UTC, edylcrm approved these changes

2024-05-16 15:36 UTC, merged